#!/bin/bash
# Do git stuff to make a release.

. var/releaseInfo

echo "Release:
    name:    $releaseName
    version: $releaseVersion"

set -ex
git add app/app-release.apk var/releaseInfo "$gradleFile"
git commit -m 'Made release $releaseName.'

git tag -a "$releaseName" -m "Release $releaseName ($releaseVersion)"
git pull
git push
git push --tags

